version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: tuushin_crm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
      POSTGRES_DB: ${POSTGRES_DB:-tuushin_crm}
    # Expose DB on host port 5436 -> container 5432
    ports:
      - '5436:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
