export interface Quotation {
  id: string;
  quotationNumber: string;
  client: string;
  origin: string;
  destination: string;
  cargoType: string;
  weight?: number;
  volume?: number;
  estimatedCost: number;
  createdAt: string;
  createdBy: string;
  // Optional workflow status for dashboard summaries
  status?: 'CANCELLED' | 'CREATED' | 'QUOTATION' | 'CONFIRMED' | 'ONGOING' | 'ARRIVED' | 'RELEASED' | 'CLOSED';
  // Extended optional fields to match filters/columns
  registrationNo?: string;
  containerOrWagon?: string;
  incoterm?: string;
  type?: string;
  ownership?: string;
  releaseOrder?: string;
  shipper?: string;
  country?: string;
  cr?: string;
  crDays?: number;
  carrier?: string;
  agent1?: string;
  agent2?: string;
  agent3?: string;
  responsibleSpecialist?: string;
  loadedDate?: string;
  transitWh?: string;
  arrivedAtTransitWhDate?: string;
  loadedFromTransitWhDate?: string;
  arrivedAtBorderDate?: string;
  departedBorderDate?: string;
  arrivedInUBDate?: string;
  unloadingYard?: string;
  devannedDate?: string;
  emptyReturnedDate?: string;
  wagonNoEmptyReturn?: string;
  returnArrivedAtBorderDate?: string;
  returnDepartedBorderDate?: string;
  exportedDate?: string;
  transferredToOthersDate?: string;
  transferNote?: string;
  transferredTo?: string;
  salesManager?: string;
  goods?: string;
  salesDate?: string;
  freightCharge?: number;
  paidDate?: string;
  paymentStatus?: string;
  amountPaid?: number;
}
